name: Eisbär's Place
description: This is the Place from Eisbär, nothing to see here right now!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
